embedding_size: 64
n_layers: 2
reg_weight: [0.0001, 0.001, 0.01, 0.1]
learning_rate: [0.0001, 0.001, 0.01]
k: [1, 2]
s_weight: [1, 0.1, 0.01, 0.001, 0]

hyper_parameters: ["reg_weight", "learning_rate", 'k', 's_weight']

